repos:
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "v2.29.0"
  hooks:
    - id: pyproject-fmt

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.5
  hooks:
    - id: ruff-check
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v2.3.1'
  hooks:
    - id: mypy
      args: []
      additional_dependencies:
        - "pytest==7.2.0"
        - "tomli"