repos:
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "v2.16.2"
  hooks:
    - id: pyproject-fmt

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.2
  hooks:
    - id: ruff-check
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.19.1'
  hooks:
    - id: mypy
      args: []
      additional_dependencies:
        - "pytest==7.2.0"
        - "tomli"